"use client";

import { Download, Lock, Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface DownloadSectionProps {
  skillName: string;
  skillId: string;
}

export function DownloadSection({ skillName, skillId }: DownloadSectionProps) {
  const handleFreeDownload = () => {
    // In production this would trigger actual skill file generation/download
    const content = `# ${skillName}\n# .skill file\n# Generated by CreateSkills.xyz\n# ID: ${skillId}\n\nskill_id: "${skillId}"\nversion: "1.0.0"\ntype: "core"\n`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${skillName}.skill`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      {/* Free */}
      <Card className="relative">
        <CardHeader>
          <Badge variant="accent" className="w-fit mb-2">Free</Badge>
          <CardTitle className="text-base">Core Skill File</CardTitle>
          <CardDescription>
            Download the <code className="text-xs text-emerald-400">core.skill</code> + README. Deploy to any agent immediately.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="text-xs text-white/40 space-y-1 mb-4">
            <li>✓ core.skill — knowledge graph</li>
            <li>✓ README.md — overview</li>
          </ul>
          <Button
            onClick={handleFreeDownload}
            variant="outline"
            className="w-full gap-2"
          >
            <Download className="w-4 h-4" />
            Download .skill
          </Button>
        </CardContent>
      </Card>

      {/* Pro */}
      <Card className="relative overflow-hidden">
        {/* Coming soon overlay */}
        <div
          className="absolute inset-0 z-10 flex flex-col items-center justify-center rounded-xl"
          style={{ background: "rgba(0,0,0,0.6)", backdropFilter: "blur(2px)" }}
        >
          <Badge variant="muted" className="mb-2">Coming Soon</Badge>
          <p className="text-xs text-white/30 text-center px-4">
            Pro unlock + Marketplace listing
          </p>
        </div>
        <CardHeader>
          <Badge variant="default" className="w-fit mb-2">Pro · $19</Badge>
          <CardTitle className="text-base">Full Skill Package</CardTitle>
          <CardDescription>
            Complete package with prompts, tools, and manifest. List on the marketplace.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="text-xs text-white/40 space-y-1 mb-4">
            <li>✓ Everything in Free</li>
            <li>✓ prompts/ — curated templates</li>
            <li>✓ tools/ — tool call definitions</li>
            <li>✓ manifest.json — full metadata</li>
            <li>✓ Marketplace listing</li>
          </ul>
          <Button disabled className="w-full gap-2">
            <Lock className="w-4 h-4" />
            Unlock for $19
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
